开始执行时间：2025-08-25 17:25:40
正在运行脚本：..\01-批量拉取到本地\copy_to_local.py
脚本 ..\01-批量拉取到本地\copy_to_local.py 运行失败。
错误信息：
Traceback (most recent call last):
  File "D:\JA\database\01-鎵归噺鎷夊彇鍒版湰鍦癨copy_to_local.py", line 1, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'

脚本 ..\01-批量拉取到本地\copy_to_local.py 运行失败，停止后续脚本执行。
结束执行时间：2025-08-25 17:25:40
2025-08-25 17:29:31,283 - INFO - ==================================================
2025-08-25 17:29:31,283 - INFO - 开始执行流水线 - 2025-08-25 17:29:31
2025-08-25 17:29:31,283 - INFO - 虚拟环境路径: D:\JA\database\.venv
2025-08-25 17:29:31,284 - INFO - Python版本: 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
2025-08-25 17:29:31,349 - INFO - pymysql版本: 1.4.6
2025-08-25 17:29:31,349 - INFO - 正在运行脚本: ..\01-批量拉取到本地\copy_to_local.py
2025-08-25 17:29:31,349 - INFO - 尝试运行脚本: D:\JA\database\01-批量拉取到本地\copy_to_local.py
2025-08-25 17:29:31,349 - INFO - 当前工作目录: D:\JA\database\00-按顺序批量执行
2025-08-25 17:29:31,349 - INFO - Python解释器路径: D:\JA\database\.venv\Scripts\python.exe
2025-08-25 17:30:54,504 - INFO - ==================================================
2025-08-25 17:30:54,504 - INFO - 开始执行流水线 - 2025-08-25 17:30:54
2025-08-25 17:30:54,504 - INFO - 虚拟环境路径: D:\JA\database\.venv
2025-08-25 17:30:54,504 - INFO - Python版本: 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
2025-08-25 17:30:54,533 - INFO - pymysql版本: 1.4.6
2025-08-25 17:30:54,533 - INFO - 正在运行脚本: ..\01-批量拉取到本地\copy_to_local.py
2025-08-25 17:30:54,533 - INFO - 开始运行脚本: D:\JA\database\01-批量拉取到本地\copy_to_local.py
2025-08-25 17:30:54,533 - INFO - 工作目录: D:\JA\database\01-批量拉取到本地
2025-08-25 17:30:55,029 - INFO - [..\01-批量拉取到本地\copy_to_local.py] 开始数据库同步任务: 2025-08-25 17:30:55
2025-08-25 17:31:15,756 - INFO - ==================================================
2025-08-25 17:31:15,757 - INFO - 开始执行流水线 - 2025-08-25 17:31:15
2025-08-25 17:31:15,757 - INFO - 虚拟环境路径: D:\JA\database\.venv
2025-08-25 17:31:15,757 - INFO - Python版本: 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
2025-08-25 17:31:15,783 - INFO - pymysql版本: 1.4.6
2025-08-25 17:31:15,783 - INFO - 正在运行脚本: ..\01-批量拉取到本地\copy_to_local.py
2025-08-25 17:31:15,783 - INFO - 开始运行脚本: D:\JA\database\01-批量拉取到本地\copy_to_local.py
2025-08-25 17:31:15,783 - INFO - 工作目录: D:\JA\database\01-批量拉取到本地
2025-08-25 17:31:16,251 - INFO - [..\01-批量拉取到本地\copy_to_local.py] 开始数据库同步任务: 2025-08-25 17:31:16
2025-08-25 17:32:39,057 - INFO - ==================================================
2025-08-25 17:32:39,057 - INFO - 开始执行流水线 - 2025-08-25 17:32:39
2025-08-25 17:32:39,058 - INFO - 虚拟环境路径: D:\JA\database\.venv
2025-08-25 17:32:39,058 - INFO - Python版本: 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
2025-08-25 17:32:39,104 - INFO - pymysql版本: 1.4.6
2025-08-25 17:32:39,104 - INFO - 正在运行脚本: ..\01-批量拉取到本地\copy_to_local.py
2025-08-25 17:32:39,104 - INFO - 开始运行脚本: D:\JA\database\01-批量拉取到本地\copy_to_local.py
2025-08-25 17:32:39,104 - INFO - 工作目录: D:\JA\database\01-批量拉取到本地
2025-08-25 17:32:39,744 - INFO - [..\01-批量拉取到本地\copy_to_local.py] 开始数据库同步任务: 2025-08-25 17:32:39
